-- Core config (must load first)
require('user.core')
require('user.autocmds')

-- Plugins (order matters for dependencies)
require('user.plugins.plugins')
require('user.plugins.theme')
require('user.plugins.lsp')
require('user.plugins.completion')
require('user.plugins.treesitter')
require('user.plugins.fzf')
require('user.plugins.supermaven')
require('user.plugins.neoscroll')
require('user.plugins.dap')
require('user.plugins.oil')
require('user.plugins.markdown')
require('user.plugins.codediff')
require('user.plugins.alpha')
require('user.plugins.terminal')

-- User config
require('user.keymaps')